version: "3.1"
services:
 frontend:
    build: ./frontend
    container_name: frontend_container
    # volumes:
    #   - "./frontend:/frontend"
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - api

 api:
    build: ./api
    container_name: api_container
    # volumes:
    #   - "./api:/api"
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/inventory_db
    depends_on:
      - db

 db:
    image: postgres:latest
    container_name: db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: inventory_db
    # volumes:
    #   - ./db:/var/lib/postgresql/data
    networks:
      - app-network

networks:
 app-network:
    driver: bridge